# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write
  
concurrency:
  group: "pages-${{ github.event.pull_request.number || github.run_id }}"
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: pr-preview-${{ github.event.pull_request.number || github.run_id }}
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Setup Hugo (Extended)
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.9'
          extended: true
      - name: Install dependencies
        run: make setup
      - name: Build Academy
        run: make build-preview BASEURL=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-preview-${{ github.event.pull_request.number || github.run_id }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload just the public folder
          path: 'public'
      - name: Deploy to GitHub Pages
        if: github.event.pull_request.head.repo.full_name == github.repository
        id: deployment
        uses: actions/deploy-pages@v4







      - name: Commit changes
        if: github.event.pull_request.head.repo.full_name != github.repository
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: mesheryctl/helpers server/helpers/ **.go docs/
          commit_user_name: l5io
          commit_user_email: ci@meshery.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "Deployment preview for PR ${{ github.event.pull_request.number }}"

      # - name: Set up Git user
      #   if: github.event.pull_request.head.repo.full_name != github.repository
      #   run: |
      #     git config user.name "l5io"
      #     git config user.email "l5io@users.noreply.github.com"
      # - name: Push branch to master repo
      #   if: github.event.pull_request.head.repo.full_name != github.repository
      #   run: |
      #     git remote add main-origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      #     git push main-origin HEAD:refs/heads/pr-preview/${{ github.event.pull_request.number }} --force


      - name: Comment Preview URL on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            ðŸš€ **Preview deployment for PR #${{ github.event.pull_request.number }}**
            
            ðŸŒ PR URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pr-preview-${{ github.event.pull_request.number || github.run_id }}
            > ðŸ“– General Preview: ${{ steps.deployment.outputs.page_url }}
            
            This preview will be updated automatically when you push new commits to this PR.









  # mirror-fork-pr:
  #   if: github.event.pull_request.head.repo.full_name != github.repository
  #   environment:
  #     name: pr-preview-${{ github.event.pull_request.number || github.run_id }}
  #     # url: ${{ steps.deployment.outputs.page_url }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout PR branch
  #       uses: actions/checkout@v4
  #       with:
  #         ref: ${{ github.event.pull_request.head.ref }}
  #         repository: ${{ github.event.pull_request.head.repo.full_name }}
